version: "3"
services:
  server:
    build: auth-server
    volumes:
      - ./:/app
    ports:
      - 8181:3000
    env_file:
      - auth-server/.env
    links:
      - database
    command: ['npm', 'start']
    networks:
      - dev
  database:
    image: mariadb
    container_name: db_docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - dev
  www:
    build: php
    container_name: www_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev



volumes:
  db-data:


networks:
  dev:
